name: quality-checks

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint-command:
          - npm run lint:js
          - npm run lint:md
          - npm run lint:md:relative-urls
          - npm run lint:md:external-urls
          - npm run lint:md:consistency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: ${{ matrix.lint-command }}
